spec-version: 0.30.0
name: monoidal
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

source-dirs: src
dependencies:
  - { name: "base", version: ">=4.12 && <4.13" }
  - bifunctors
  - profunctors
  - these
  - hedgehog
  - tasty
  - tasty-hedgehog

ghc-options: [-Wall, -Wno-orphans, -fprint-potential-instances]
default-extensions:
  - GADTs

  - StandaloneDeriving
  - DeriveFunctor
  - DerivingVia
  - GeneralizedNewtypeDeriving

  - ScopedTypeVariables
  - RankNTypes
  - QuantifiedConstraints

  - TypeApplications
  - TypeOperators
  - MultiParamTypeClasses

  - ConstraintKinds
  - DataKinds
  - PolyKinds
  - KindSignatures

  - UndecidableInstances
  - UndecidableSuperClasses
  - FlexibleInstances
  - FlexibleContexts
  - DefaultSignatures

  - TypeFamilies
  - TypeFamilyDependencies

  - AllowAmbiguousTypes

library: {}
tests:
  monoidal-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - monoidal
