spec-version: 0.30.0
name: monoidal
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

source-dirs: src
dependencies:
  - { name: "base", version: ">=4.12 && <4.13" }
  - bifunctors
  - profunctors

ghc-options: -Wall
default-extensions:
  - GADTs

  - StandaloneDeriving
  - DeriveFunctor
  - DerivingVia
  - GeneralizedNewtypeDeriving

  - ScopedTypeVariables
  - RankNTypes
  - QuantifiedConstraints

  - TypeApplications
  - TypeOperators
  - MultiParamTypeClasses

  - ConstraintKinds
  - DataKinds
  - PolyKinds
  - KindSignatures

  - UndecidableInstances
  - FlexibleInstances
  - FlexibleContexts
  - DefaultSignatures

  - TypeFamilies
  - TypeFamilyDependencies

library: {}
