spec-version: 0.30.0
name: monoidal
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

ghc-options: [-Wall, -Wno-orphans, -fprint-potential-instances, -fno-show-valid-hole-fits]
default-extensions:
  - GADTs

  - StandaloneDeriving
  - DeriveFunctor
  - DerivingVia
  - GeneralizedNewtypeDeriving

  - ScopedTypeVariables
  - RankNTypes
  - QuantifiedConstraints

  - TypeApplications
  - TypeOperators
  - MultiParamTypeClasses

  - ConstraintKinds
  - DataKinds
  - PolyKinds
  - KindSignatures

  - UndecidableInstances
  - UndecidableSuperClasses
  - FlexibleInstances
  - FlexibleContexts
  - DefaultSignatures
  - InstanceSigs

  - TypeFamilies
  - TypeFamilyDependencies

  - AllowAmbiguousTypes

dependencies:
  - { name: "base", version: ">=4.13 && <4.14" }
  - bifunctors
  - profunctors
  - these

library:
  source-dirs: src

tests:
  monoidal-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - monoidal
      - hedgehog
      - tasty
      - tasty-hedgehog
